### ISSUE TITLE
Tests probably shouldn't require `write` authorization to the collections being ingested into

### ISSUE THREAD

**Issue by psFried** [estuary/animated-carnival#18]
Say you have a test:

```yaml
tests:
  coyote/anvils/does_the_thing_when_anvil_is_dropped:
    - ingest:
        collection: acmeCo/anvils
        documents: [...]
    - verify:
        collection: coyote/anvils/drops
        documents: [...]
```

Flow currently checks that the role `coyote/anvils/does_the_thing_when_anvil_is_dropped` has `write` capability to `acmeCo/anvils`. I think we should consider easing that restriction to only require `read` access, which would make it possible to write tests for derivations that read from collections you don't have `write` access to.
